version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: "./docker/nginx/Dockerfile"
    ports:
      - 80:80
    depends_on:
      - rails
  rails:
    build:
      context: .
      dockerfile: "./docker/rails/Dockerfile.dev"
    ports:
      - 3000:3000
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - "./app:/app"
      - "bundle:/usr/local/bundle"
    depends_on:
      - postgres
    env_file: "./common.env"
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file: "./common.env"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
  bundle: