FROM ruby:latest
RUN apt-get update -qq && \
    apt-get install -y apt-utils \
    build-essential \
    libpq-dev \
    nodejs \
    mysql-client
RUN mkdir /app
RUN groupadd -g 1000 rails && useradd -u 1000 -m -g rails rails
USER rails:rails
WORKDIR /app
ADD --chown=rails:rails ./app/Gemfile /app/Gemfile
ADD --chown=rails:rails ./app/Gemfile.lock /app/Gemfile.lock
RUN bundle install -j4
ADD ./app /app

EXPOSE 3000